using Remedy.Framework;
using Remedy.Schematics;
//using SaintsField;
using System.Collections.Generic;
using UnityEngine;

public class GlobalSchematicManagerData : SingletonData<GlobalSchematicManagerData>
{
    [Tooltip("The Schematic Prefabs generated by the Schematics system from the FlowGraphEditorWindow. (Key: GameObject Prefab - " +
        "Value: SchematicScope Asset)")]
    [SerializeField]
    private SerializableDictionary<GameObject, SchematicScope> _schematicPrefabs = new();
    public static SerializableDictionary<GameObject, SchematicScope> SchematicPrefabs => Instance._schematicPrefabs;

    [SerializeField]
    private SerializableDictionary<GameObject, List<int>> _prefabIOBases = new();
    public static SerializableDictionary<GameObject, List<int>> PrefabIOBases => Instance._prefabIOBases;

    [Tooltip("The Singletons Objects created by the Schematic Editor")]
    [SerializeField]
    private SchematicInstanceController[] Singletons = new SchematicInstanceController[0];
}